# Generated by Django 6.0.2 on 2026-02-15 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinic', '0001_initial'),
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('fabricante', models.CharField(max_length=100)),
                ('lote', models.CharField(max_length=50)),
                ('data_fabricacao', models.DateField()),
                ('data_validade', models.DateField()),
                ('descricao', models.CharField(max_length=200)),
                ('especie_indicada', models.CharField(choices=[('CANINA', 'Canina'), ('FELINA', 'Felina')], max_length=10)),
                ('intervalo_doses_dias', models.IntegerField()),
                ('quantidade_estoque', models.IntegerField()),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacinas', to='clinic.clinica')),
            ],
        ),
        migrations.CreateModel(
            name='Vacinacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_aplicacao', models.DateField(auto_now_add=True)),
                ('proxima_dose', models.DateField()),
                ('observacoes', models.CharField(blank=True, max_length=200)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacinacoes', to='clinic.clinica')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacinacoes', to='pets.pets')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacinacoes', to='clinic.profissional')),
                ('vacina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aplicacoes', to='vaccines.vacina')),
            ],
        ),
    ]
