# Generated by Django 6.0.2 on 2026-02-10 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinic', '0004_alter_tutor_cpf'),
        ('pets', '0002_alter_pets_sexo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=200)),
                ('fabricante', models.CharField(max_length=100)),
                ('Clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacinas', to='clinic.clinica')),
            ],
        ),
        migrations.CreateModel(
            name='Vacinacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_aplicacao', models.DateField(auto_now_add=True)),
                ('proxima_dose', models.DateField()),
                ('observacoes', models.CharField(blank=True, max_length=200)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacinacoes', to='clinic.clinica')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacinacoes', to='pets.pets')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacinacoes', to='clinic.profissional')),
                ('vacina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aplicacoes', to='vaccines.vacina')),
            ],
        ),
    ]
