# Generated by Django 6.0.2 on 2026-02-10 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinic', '0004_alter_tutor_cpf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('especie', models.CharField(max_length=50)),
                ('raca', models.CharField(max_length=50)),
                ('sexo', models.CharField(max_length=10)),
                ('data_de_nascimento', models.DateField()),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='clinic.clinica')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='clinic.tutor')),
            ],
        ),
    ]
