# Generated by Django 6.0.2 on 2026-02-10 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pets',
            name='sexo',
            field=models.CharField(choices=[('M', 'Macho'), ('F', 'Fêmea')], max_length=10),
        ),
    ]
