# Generated by Django 6.0.2 on 2026-02-10 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('crmv', models.CharField(max_length=20)),
                ('proxima_vacina', models.CharField(max_length=150)),
                ('data_de_vacinacao', models.DateField()),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profissionais', to='clinic.clinica')),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('data_de_nascimento', models.DateField()),
                ('cpf', models.CharField()),
                ('Clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutores', to='clinic.clinica')),
            ],
        ),
    ]
