# Generated by Django 6.0.2 on 2026-02-10 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profissional',
            old_name='clinica',
            new_name='Clinica',
        ),
    ]
