# Generated by Django 6.0.2 on 2026-02-10 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_rename_clinica_profissional_clinica'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profissional',
            old_name='Clinica',
            new_name='clinica',
        ),
        migrations.RenameField(
            model_name='tutor',
            old_name='Clinica',
            new_name='clinica',
        ),
    ]
