# Generated by Django 6.0.2 on 2026-02-10 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_rename_clinica_profissional_clinica_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='cpf',
            field=models.CharField(max_length=100),
        ),
    ]
