# Generated by Django 6.0.2 on 2026-02-11 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0004_alter_tutor_cpf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profissional',
            name='data_de_vacinacao',
        ),
        migrations.RemoveField(
            model_name='profissional',
            name='proxima_vacina',
        ),
    ]
